trainingInput:
  region: europe-west4
  runtimeVersion: '2.1'
  pythonVersion: '3.7' 
  scaleTier: CUSTOM
  # Configure a master worker with 4 T4 GPUs
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_V100
